name = "sfmc-contract-health"
main = "src/app.js"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "sfmc_contract_health_db"
database_id = "953169b6-b5ac-4f1d-8988-2cd5ba8504fe"
migrations_dir = "./schema"
database_file = "./local_db/sfmc_contract_health.db"